### ISSUE TITLE
CI does not run Miri

### ISSUE THREAD

**Issue by james7132** [asynchronics/st3#7]
There's a sizable amount of unsafe being worked with in this crate but it's unclear if it's use is sound or not.  It'd be ideal if miri was run regularly and on every PR to ensure that no there's no undefined behavior in this crate.

**Comment by sbarral** [comment]
Oh yes, that's an oversight! After MIRI introduced proper support for multithreading, it was added to the CI in most `unsafe`-containing crates under the `asynchronics` domains, but `st3` was missed (and another one as I just discovered).

We should take the opportunity to modify all tests to use boxed values as queue items. This would allow MIRI to detect both leaks and destructors improperly called on freed slots. Just to set expectation right though: Loom, MIRI and better tests will never give 100% soundness guarantee, they can only make it less likely. MIRI does not exhaustively check all possible thread interleaving; Loom does, but cannot detect some unsound unsafe usages, in particular around destructors. And both are only as good as the tests they run...

I will be happy to take a PR, otherwise I will do both these things after the WE.
